spring:
  config:
    activate:
      on-profile:
      - local-sts
 
  security:
    user:
      name: john
      password: password

        
  datasource:
    url: "jdbc:postgresql://localhost:5432/db"
    username: john
    password: passwd
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      
server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:selfsigned.p12
    key-store-type: PKCS12
    key-store-password: abcd1234
    
logging:
  level:
    #web: debug
    #'[reactor.netty]': debug
    '[io.netty]': debug 

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include:
        - env
        - info
        - health
        - metrics
        - prometheus
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      #enabled: true 
---
spring:
  config:
    activate:
      on-profile:
      - microk8s

  security:
    user:
      name: john
      password: password

        
  datasource:
    #url: "jdbc:postgresql://jpadb:5432/jpa"
    #url: "jdbc:postgresql://jpadb.default.svc.cluster.local:5432/jpa"
    url: "jdbc:postgresql://jpadb-postgresql.postgres.svc.cluster.local:5432/jpa"
    username: john
    password: pass
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  http2:
    enabled: true
          
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include:
        - env
        - info
        - health
        - metrics
        - prometheus
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      #enabled: true 
      
logging:
  level:
    web: debug
    '[reactor.netty]': debug
    '[io.netty]': debug 
    